language: ruby

rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx
  - jruby
  - ruby-head

gemfile:
  - spec/gemfile/mongoid3.gemfile
  - spec/gemfile/mongoid4.gemfile
  - spec/gemfile/mongoid5.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
    - rvm: jruby
    - rvm: ruby-head

env:
  matrix:
    - MONGODB=3.2.18 CONFIG="--config /tmp/mongodb-wiredtiger.conf"
    - MONGODB=3.2.18 CONFIG="--config /tmp/mongodb-mmapv1.conf"
    - MONGODB=3.4.10 CONFIG="--config /tmp/mongodb-wiredtiger.conf"
    - MONGODB=3.6.1 CONFIG="--config /tmp/mongodb-wiredtiger.conf"

before_script:
  - cp spec/config/* /tmp/
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --version
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 $CONFIG &> /dev/null &
